const RECEIPT_STATES = {
    RECEIPT_INITIALIZED: "RECEIPT_INITIALIZED",
    RECEIPT_UPDATED: "RECEIPT_UPDATED",
    RECEIPT_SIGNED_BY_ONE_PARTY: "RECEIPT_SIGNED_BY_ONE_PARTY",
    RECEIPT_COMMITTING: "RECEIPT_COMMITTING",
    RECEIPT_FAILED_TO_COMMIT: "RECEIPT_FAILED_TO_COMMIT",
    RECEIPT_ON_CHAIN: "RECEIPT_ON_CHAIN"
};

const RECEIPT_EVENTS = {
    UPDATE_RECEIPT: "UPDATE_RECEIPT",
    SIGN_RECEIPT: "SIGN_RECEIPT",
    COMMIT_RECEIPT: "COMMIT_RECEIPT",
    RECEIPT_COMMIT_FAILED: "RECEIPT_COMMIT_FAILED",
    RECEIPT_COMMITTED: "RECEIPT_COMMITTED",
};

module.exports = {RECEIPT_EVENTS, RECEIPT_STATES};
